import type { WorkflowEdge, WorkflowNode, WorkflowRun } from "@/types/workflow";

export type WorkflowTemplate = {
  id: string;
  name: string;
  description: string;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  runs: WorkflowRun[];
};

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: "ghibli-campaign",
    name: "Ghibli Campaign",
    description: "Stylize a hero image, crop the focal frame, extract a video still, and brief the launch story.",
    nodes: [
      {
        id: "upload-image-1",
        type: "uploadImage",
        position: { x: 80, y: 220 },
        data: {
          label: "Upload Image",
          nodeType: "uploadImage",
          description: "Transloadit powered media input",
          fileName: "mountain-scene.webp",
          imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
          outputKind: "image",
        },
      },
      {
        id: "text-style-1",
        type: "text",
        position: { x: 80, y: 20 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Prompt or structured text",
          role: "system",
          text: "Studio Ghibli inspired, painterly, warm light, whimsical atmosphere, cinematic composition.",
          outputKind: "text",
        },
      },
      {
        id: "text-prompt-1",
        type: "text",
        position: { x: 80, y: 420 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Prompt or structured text",
          role: "message",
          text: "Transform this landscape into a soft Ghibli-style illustration while keeping the sunset mood and valley depth.",
          outputKind: "text",
        },
      },
      {
        id: "generate-image-1",
        type: "generateImage",
        position: { x: 460, y: 210 },
        data: {
          label: "Generate Image",
          nodeType: "generateImage",
          description: "Gemini image generation",
          model: "gemini-3.1-flash-image-preview",
          systemPrompt: "",
          userMessage: "",
          connectedImages: [],
          result: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=1400&q=80",
          outputKind: "image",
        },
      },
      {
        id: "crop-image-1",
        type: "cropImage",
        position: { x: 860, y: 210 },
        data: {
          label: "Crop Image",
          nodeType: "cropImage",
          description: "FFmpeg crop task",
          imageUrl: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=1400&q=80",
          xPercent: "18",
          yPercent: "12",
          widthPercent: "64",
          heightPercent: "70",
          result: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=900&q=80",
          outputKind: "image",
        },
      },
      {
        id: "upload-video-1",
        type: "uploadVideo",
        position: { x: 80, y: 760 },
        data: {
          label: "Upload Video",
          nodeType: "uploadVideo",
          description: "Transloadit video input",
          fileName: "campaign-cut.mp4",
          videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
          outputKind: "video",
        },
      },
      {
        id: "extract-frame-1",
        type: "extractFrame",
        position: { x: 460, y: 760 },
        data: {
          label: "Extract Frame",
          nodeType: "extractFrame",
          description: "FFmpeg still frame task",
          videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
          timestamp: "40%",
          result: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80",
          outputKind: "image",
        },
      },
      {
        id: "llm-system-2",
        type: "text",
        position: { x: 860, y: 620 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Prompt or structured text",
          role: "system",
          text: "You are a launch strategist. Summarize the visual direction and suggest a creative campaign angle.",
          outputKind: "text",
        },
      },
      {
        id: "llm-message-2",
        type: "text",
        position: { x: 860, y: 900 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Prompt or structured text",
          role: "message",
          text: "Create a short creative brief based on the generated hero image and the extracted video frame.",
          outputKind: "text",
        },
      },
      {
        id: "llm-1",
        type: "runLLM",
        position: { x: 1260, y: 760 },
        data: {
          label: "Run Any LLM",
          nodeType: "runLLM",
          description: "Gemini via Trigger.dev",
          model: "gemini-2.5-flash-lite",
          systemPrompt: "",
          userMessage: "",
          acceptedImageCount: 4,
          connectedImages: [],
          result:
            "Creative brief: lead with the hand-painted hero art, use the extracted motion frame for contrast, and anchor the campaign around warmth, wonder, and crafted storytelling.",
          outputKind: "text",
        },
      },
    ],
    edges: [
      { id: "e-1", source: "text-style-1", target: "generate-image-1", sourceHandle: "output", targetHandle: "system_prompt", animated: true },
      { id: "e-2", source: "text-prompt-1", target: "generate-image-1", sourceHandle: "output", targetHandle: "user_message", animated: true },
      { id: "e-3", source: "upload-image-1", target: "generate-image-1", sourceHandle: "output", targetHandle: "images", animated: true },
      { id: "e-4", source: "generate-image-1", target: "crop-image-1", sourceHandle: "output", targetHandle: "image_url", animated: true },
      { id: "e-5", source: "upload-video-1", target: "extract-frame-1", sourceHandle: "output", targetHandle: "video_url", animated: true },
      { id: "e-6", source: "llm-system-2", target: "llm-1", sourceHandle: "output", targetHandle: "system_prompt", animated: true },
      { id: "e-7", source: "llm-message-2", target: "llm-1", sourceHandle: "output", targetHandle: "user_message", animated: true },
      { id: "e-8", source: "crop-image-1", target: "llm-1", sourceHandle: "output", targetHandle: "images", animated: true },
      { id: "e-9", source: "extract-frame-1", target: "llm-1", sourceHandle: "output", targetHandle: "images", animated: true },
    ],
    runs: [
      {
        id: "run-sample-1",
        workflowId: "sample-workflow",
        scope: "full",
        status: "success",
        startedAt: "2026-03-30T18:20:00.000Z",
        durationMs: 9100,
        summary: "Generated a stylized hero image, cropped the focal area, extracted a supporting video frame, and summarized the creative direction.",
        nodeRuns: [
          {
            nodeId: "generate-image-1",
            nodeLabel: "Generate Image",
            nodeType: "generateImage",
            status: "success",
            executionMs: 4200,
            inputs: ["Style guidance connected", "Prompt ready", "1 reference image"],
            output: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=1400&q=80",
          },
          {
            nodeId: "crop-image-1",
            nodeLabel: "Crop Image",
            nodeType: "cropImage",
            status: "success",
            executionMs: 1600,
            inputs: ["Image input connected", "x=18 y=12 w=64 h=70"],
            output: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?auto=format&fit=crop&w=900&q=80",
          },
          {
            nodeId: "extract-frame-1",
            nodeLabel: "Extract Frame",
            nodeType: "extractFrame",
            status: "success",
            executionMs: 1100,
            inputs: ["Video input connected", "timestamp=40%"],
            output: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80",
          },
          {
            nodeId: "llm-1",
            nodeLabel: "Run Any LLM",
            nodeType: "runLLM",
            status: "success",
            executionMs: 2200,
            inputs: ["System prompt connected", "User message ready", "2 image inputs"],
            output:
              "Creative brief: lead with the hand-painted hero art, use the extracted motion frame for contrast, and anchor the campaign around warmth, wonder, and crafted storytelling.",
          },
        ],
      },
    ],
  },
  {
    id: "product-cutdown",
    name: "Product Cutdown",
    description: "Upload a product shot, crop variants, and generate concise launch copy for the hero treatment.",
    nodes: [
      {
        id: "product-image",
        type: "uploadImage",
        position: { x: 100, y: 280 },
        data: {
          label: "Upload Image",
          nodeType: "uploadImage",
          description: "Primary product shot",
          fileName: "product-shot.webp",
          imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=80",
          outputKind: "image",
        },
      },
      {
        id: "crop-hero",
        type: "cropImage",
        position: { x: 480, y: 220 },
        data: {
          label: "Crop Image",
          nodeType: "cropImage",
          description: "Hero crop",
          imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=80",
          xPercent: "10",
          yPercent: "8",
          widthPercent: "62",
          heightPercent: "72",
          result: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=960&q=80",
          outputKind: "image",
        },
      },
      {
        id: "copy-system",
        type: "text",
        position: { x: 480, y: 560 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Tone definition",
          role: "system",
          text: "You are a premium DTC brand strategist. Keep the tone crisp, elevated, and conversion-minded.",
          outputKind: "text",
        },
      },
      {
        id: "copy-message",
        type: "text",
        position: { x: 480, y: 780 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Copy prompt",
          role: "message",
          text: "Write a homepage hero headline, supporting line, and 3 feature bullets for this product image.",
          outputKind: "text",
        },
      },
      {
        id: "copy-llm",
        type: "runLLM",
        position: { x: 900, y: 650 },
        data: {
          label: "Run Any LLM",
          nodeType: "runLLM",
          description: "Gemini via Trigger.dev",
          model: "gemini-2.5-flash-lite",
          systemPrompt: "",
          userMessage: "",
          acceptedImageCount: 4,
          connectedImages: [],
          result: "Headline: Designed to disappear into your day. Supporting line: A refined wearable that keeps every signal within reach without stealing attention.",
          outputKind: "text",
        },
      },
    ],
    edges: [
      { id: "pc-1", source: "product-image", target: "crop-hero", sourceHandle: "output", targetHandle: "image_url", animated: true },
      { id: "pc-2", source: "copy-system", target: "copy-llm", sourceHandle: "output", targetHandle: "system_prompt", animated: true },
      { id: "pc-3", source: "copy-message", target: "copy-llm", sourceHandle: "output", targetHandle: "user_message", animated: true },
      { id: "pc-4", source: "crop-hero", target: "copy-llm", sourceHandle: "output", targetHandle: "images", animated: true },
    ],
    runs: [],
  },
  {
    id: "video-social",
    name: "Video Social Clip",
    description: "Pull a still from video, pair it with a campaign prompt, and produce social-ready copy in one pass.",
    nodes: [
      {
        id: "video-source",
        type: "uploadVideo",
        position: { x: 120, y: 280 },
        data: {
          label: "Upload Video",
          nodeType: "uploadVideo",
          description: "Campaign cut",
          fileName: "campaign-cut.mp4",
          videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
          outputKind: "video",
        },
      },
      {
        id: "video-frame",
        type: "extractFrame",
        position: { x: 500, y: 280 },
        data: {
          label: "Extract Frame",
          nodeType: "extractFrame",
          description: "Hero still",
          videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
          timestamp: "25%",
          result: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80",
          outputKind: "image",
        },
      },
      {
        id: "social-message",
        type: "text",
        position: { x: 500, y: 640 },
        data: {
          label: "Text",
          nodeType: "text",
          description: "Social prompt",
          role: "message",
          text: "Write an Instagram caption, a short reel hook, and 5 punchy overlay phrases for this visual moment.",
          outputKind: "text",
        },
      },
      {
        id: "social-llm",
        type: "runLLM",
        position: { x: 930, y: 520 },
        data: {
          label: "Run Any LLM",
          nodeType: "runLLM",
          description: "Gemini via Trigger.dev",
          model: "gemini-2.5-flash-lite",
          systemPrompt: "",
          userMessage: "",
          acceptedImageCount: 4,
          connectedImages: [],
          result: "Hook: A single frame can carry the whole feeling. Caption: The quiet second before everything starts moving.",
          outputKind: "text",
        },
      },
    ],
    edges: [
      { id: "vs-1", source: "video-source", target: "video-frame", sourceHandle: "output", targetHandle: "video_url", animated: true },
      { id: "vs-2", source: "social-message", target: "social-llm", sourceHandle: "output", targetHandle: "user_message", animated: true },
      { id: "vs-3", source: "video-frame", target: "social-llm", sourceHandle: "output", targetHandle: "images", animated: true },
    ],
    runs: [],
  },
];

export const sampleNodes = workflowTemplates[0].nodes;
export const sampleEdges = workflowTemplates[0].edges;
export const sampleRuns = workflowTemplates[0].runs;
